name: ras code quality check

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Get full python version
      id: full-python-version
      run: |
        python -c "import sys; print('::set-output name=version::' + '-'.join(map(str, sys.version_info)))"
    - name: Install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source ~/.poetry/env
        poetry config virtualenvs.in-project false
        poetry config virtualenvs.path ~/.virtualenvs
        echo "~/.poetry/bin" >> $GITHUB_PATH
    - name: Install SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.HUBYO_CLIENT_ACCESS }}
        known_hosts: github.com
    - name: Cache Poetry virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('poetry.lock') }}
    - name: Install python packages
      run: |
        poetry install --no-root
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Lint
      run: |
        poetry run black --check --fast .
        poetry run flake8 --config=setup.cfg .
    - name: Static type check
      run: |
        poetry run mypy --install-types --non-interactive --config-file setup.cfg .
    - name: Make migrations files
      run: |
        poetry run python manage.py makemigrations
      env:
        DJANGO_SECRET_KEY: test_django_secret_key
    - name: unit test
      run: |
        poetry run pytest
      env:
        DJANGO_SECRET_KEY: test_django_secret_key
